In [6]:
#Matrisin üssünü alma
import numpy as np
M1 = np.array([[1,2], [4,5]])
M1

array([[1, 2],
       [4, 5]])

In [3]:
M1@M1@M1

array([[ 57,  78],
       [156, 213]])

In [4]:
np.linalg.matrix_power(M1, 3)

array([[ 57,  78],
       [156, 213]])

In [5]:
#tensörler
T1 = np.array([
  [[1,2,3], [4,5,6], [7,8,9]],
  [[10,20,30], [40,50,60], [70,80,90]],
  [[100,200,300], [400,500,600], [700,800,900]],
])

T1

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 10,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90]],

       [[100, 200, 300],
        [400, 500, 600],
        [700, 800, 900]]])

In [7]:
T2 = np.array([
    [[0,0,0], [0,0,0], [0,0,0]],
    [[1,1,1], [1,1,1], [1,1,1]],
    [[2,2,2], [2,2,2], [2,2,2]]
])

T2

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]])

In [8]:
A = T1 + T2
A

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 11,  21,  31],
        [ 41,  51,  61],
        [ 71,  81,  91]],

       [[102, 202, 302],
        [402, 502, 602],
        [702, 802, 902]]])

In [9]:
np.add(T1, T2)

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 11,  21,  31],
        [ 41,  51,  61],
        [ 71,  81,  91]],

       [[102, 202, 302],
        [402, 502, 602],
        [702, 802, 902]]])

In [10]:
S = T1 - T2
S

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[  9,  19,  29],
        [ 39,  49,  59],
        [ 69,  79,  89]],

       [[ 98, 198, 298],
        [398, 498, 598],
        [698, 798, 898]]])

In [11]:
np.subtract(T1, T2)

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[  9,  19,  29],
        [ 39,  49,  59],
        [ 69,  79,  89]],

       [[ 98, 198, 298],
        [398, 498, 598],
        [698, 798, 898]]])

In [12]:
P = T1 * T2
P

array([[[   0,    0,    0],
        [   0,    0,    0],
        [   0,    0,    0]],

       [[  10,   20,   30],
        [  40,   50,   60],
        [  70,   80,   90]],

       [[ 200,  400,  600],
        [ 800, 1000, 1200],
        [1400, 1600, 1800]]])

In [13]:
np.multiply(T1, T2)

array([[[   0,    0,    0],
        [   0,    0,    0],
        [   0,    0,    0]],

       [[  10,   20,   30],
        [  40,   50,   60],
        [  70,   80,   90]],

       [[ 200,  400,  600],
        [ 800, 1000, 1200],
        [1400, 1600, 1800]]])

In [14]:
D = T1 / T2
D

<ipython-input-14-f9444d3a0924>:1: RuntimeWarning: divide by zero encountered in true_divide
  D = T1 / T2


array([[[ inf,  inf,  inf],
        [ inf,  inf,  inf],
        [ inf,  inf,  inf]],

       [[ 10.,  20.,  30.],
        [ 40.,  50.,  60.],
        [ 70.,  80.,  90.]],

       [[ 50., 100., 150.],
        [200., 250., 300.],
        [350., 400., 450.]]])

In [15]:
np.divide(T1, T2)

<ipython-input-15-b885ab1f8362>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(T1, T2)


array([[[ inf,  inf,  inf],
        [ inf,  inf,  inf],
        [ inf,  inf,  inf]],

       [[ 10.,  20.,  30.],
        [ 40.,  50.,  60.],
        [ 70.,  80.,  90.]],

       [[ 50., 100., 150.],
        [200., 250., 300.],
        [350., 400., 450.]]])

In [16]:
np.tensordot(T1, T2)

array([[  63,   63,   63],
       [ 630,  630,  630],
       [6300, 6300, 6300]])

In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math
import warnings
warnings.filterwarnings("ignore")

In [18]:
#Seriler
v = np.array([1,2,3,4,5,6,7])
s1 = pd.Series(v)
s1

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int32

In [19]:
s1.dtype

dtype('int32')

In [20]:
s1.nbytes

28

In [21]:
s1.shape

(7,)

In [22]:
len(s1)

7

In [23]:
s1.count()

7

In [24]:
s0 = pd.Series([1,2,3], index=['a', 'b', 'c'])
s0

a    1
b    2
c    3
dtype: int64

In [25]:
s1.index = ['a', 'b', 'c', 'd', 'e', 'f', 'g']
s1

a    1
b    2
c    3
d    4
e    5
f    6
g    7
dtype: int32

In [26]:
v2 = np.random.random(10)
ind2 = np.arange(0,10)
s = pd.Series(v2, ind2)
v2, ind2, s

(array([0.772468  , 0.44046586, 0.44372082, 0.58900377, 0.23963855,
        0.05385055, 0.67932244, 0.80904876, 0.21788416, 0.50798569]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 0    0.772468
 1    0.440466
 2    0.443721
 3    0.589004
 4    0.239639
 5    0.053851
 6    0.679322
 7    0.809049
 8    0.217884
 9    0.507986
 dtype: float64)

In [27]:
dict1 = {'a1':10, 'a2':20, 'a3':30, 'a4':40}
s3 = pd.Series(dict1)
s3

a1    10
a2    20
a3    30
a4    40
dtype: int64

In [28]:
pd.Series(99, index = [0,1,2,3,4,5])

0    99
1    99
2    99
3    99
4    99
5    99
dtype: int64

In [29]:
s

0    0.772468
1    0.440466
2    0.443721
3    0.589004
4    0.239639
5    0.053851
6    0.679322
7    0.809049
8    0.217884
9    0.507986
dtype: float64

In [30]:
s[:]

0    0.772468
1    0.440466
2    0.443721
3    0.589004
4    0.239639
5    0.053851
6    0.679322
7    0.809049
8    0.217884
9    0.507986
dtype: float64

In [31]:
s[0:3]

0    0.772468
1    0.440466
2    0.443721
dtype: float64

In [33]:
s[-1:]

9    0.507986
dtype: float64

In [34]:
s[:4]

0    0.772468
1    0.440466
2    0.443721
3    0.589004
dtype: float64

In [35]:
s[:-1]

0    0.772468
1    0.440466
2    0.443721
3    0.589004
4    0.239639
5    0.053851
6    0.679322
7    0.809049
8    0.217884
dtype: float64

In [36]:
s2 = s1.copy()
s2

a    1
b    2
c    3
d    4
e    5
f    6
g    7
dtype: int32

In [37]:
s3

a1    10
a2    20
a3    30
a4    40
dtype: int64

In [38]:
s4 = s2.append(s3)
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
a4    40
dtype: int64

In [39]:
s4.drop('a4', inplace = False)

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
dtype: int64

In [40]:
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
a4    40
dtype: int64

In [41]:
s4.drop('a4', inplace = True)

In [42]:
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
dtype: int64

In [43]:
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
dtype: int64

In [44]:
s4 = s4.append(pd.Series({'a4':7}))
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
a4     7
dtype: int64

In [45]:
v1 = np.array([10,20,30])
v2 = np.array([1,2,3])
s1 = pd.Series(v1)
s2 = pd.Series(v2)
s1, s2

(0    10
 1    20
 2    30
 dtype: int32,
 0    1
 1    2
 2    3
 dtype: int32)

In [46]:
s1.add(s2)

0    11
1    22
2    33
dtype: int32

In [47]:
s1.sub(s2)

0     9
1    18
2    27
dtype: int32

In [48]:
s1.subtract(s2)

0     9
1    18
2    27
dtype: int32

In [49]:
s1.add(9)

0    19
1    29
2    39
dtype: int32

In [50]:
s1.mul(s2)

0    10
1    40
2    90
dtype: int32

In [51]:
s1.multiply(s2)

0    10
1    40
2    90
dtype: int32

In [52]:
s1.divide(s2)

0    10.0
1    10.0
2    10.0
dtype: float64

In [54]:
s1.div(s2)

0    10.0
1    10.0
2    10.0
dtype: float64

In [55]:
s1.max()

30

In [56]:
s1.min()

10

In [57]:
s5 = pd.Series([1,1,2,2,3,3], index = [0,1,2,3,4,5])
s5

0    1
1    1
2    2
3    2
4    3
5    3
dtype: int64

In [58]:
s5.value_counts()

1    2
2    2
3    2
dtype: int64

In [59]:
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [60]:
lang = ['Java', 'Python', 'C', 'C++']
df = pd.DataFrame(lang)
df

0
0    Java
1  Python
2       C
3     C++

In [61]:
rating = [1,2,3,4]
df[1] = rating
df

0  1
0    Java  1
1  Python  2
2       C  3
3     C++  4

In [62]:
df.columns = ['Language', 'Rating']
df

Language  Rating
0     Java       1
1   Python       2
2        C       3
3      C++       4

In [63]:
data = [{'a':1, 'b':2}, {'a':5, 'b':10, 'c':20}]

df2 = pd.DataFrame(data)
df3 = pd.DataFrame(data, index = ['row1', 'row2'], columns = ['a', 'b'])
df4 = pd.DataFrame(data, index = ['row1', 'row2'], columns = ['a', 'b', 'c'])
df5 = pd.DataFrame(data, index = ['row1', 'row2'], columns = ['a', 'b', 'c', 'd'])

In [64]:
df2

a   b     c
0  1   2   NaN
1  5  10  20.0

In [65]:
df3

a   b
row1  1   2
row2  5  10

In [66]:
df4

a   b     c
row1  1   2   NaN
row2  5  10  20.0

In [67]:
df5

a   b     c   d
row1  1   2   NaN NaN
row2  5  10  20.0 NaN

In [68]:
df0 = pd.DataFrame({'ID':[1,2,3,4], 'Name':['Dogu', 'Bati', 'Ross', 'John']})
df0

ID  Name
0   1  Dogu
1   2  Bati
2   3  Ross
3   4  John

In [78]:
dates = pd.date_range(start = '2022-03-14', end = '2022-03-20')
dates

DatetimeIndex(['2022-03-14', '2022-03-15', '2022-03-16', '2022-03-17',
               '2022-03-18', '2022-03-19', '2022-03-20'],
              dtype='datetime64[ns]', freq='D')

In [79]:
dates2 = pd.date_range('today', periods = 7)
dates2

DatetimeIndex(['2022-03-14 23:07:24.767238', '2022-03-15 23:07:24.767238',
               '2022-03-16 23:07:24.767238', '2022-03-17 23:07:24.767238',
               '2022-03-18 23:07:24.767238', '2022-03-19 23:07:24.767238',
               '2022-03-20 23:07:24.767238'],
              dtype='datetime64[ns]', freq='D')

In [80]:
M = np.random.random((7,7))
M

array([[0.438155  , 0.25091452, 0.54164681, 0.42650328, 0.39594743,
        0.39283023, 0.53855152],
       [0.33270018, 0.81121433, 0.61335591, 0.37094249, 0.0104957 ,
        0.44079229, 0.53236709],
       [0.15063416, 0.98100748, 0.82229311, 0.45590219, 0.30017617,
        0.60555873, 0.35327239],
       [0.35856624, 0.6821598 , 0.04660087, 0.93791904, 0.74350248,
        0.19469592, 0.11321983],
       [0.00558573, 0.26511393, 0.88135901, 0.25768422, 0.88359787,
        0.29903993, 0.45366654],
       [0.47587581, 0.7842552 , 0.97600774, 0.7008437 , 0.19826112,
        0.0129933 , 0.08111595],
       [0.05660992, 0.09345375, 0.74941715, 0.46311453, 0.47396986,
        0.61101755, 0.18962917]])

In [81]:
dframe = pd.DataFrame(M, index = dates)
dframe

0         1         2         3         4         5  \
2022-03-14  0.438155  0.250915  0.541647  0.426503  0.395947  0.392830   
2022-03-15  0.332700  0.811214  0.613356  0.370942  0.010496  0.440792   
2022-03-16  0.150634  0.981007  0.822293  0.455902  0.300176  0.605559   
2022-03-17  0.358566  0.682160  0.046601  0.937919  0.743502  0.194696   
2022-03-18  0.005586  0.265114  0.881359  0.257684  0.883598  0.299040   
2022-03-19  0.475876  0.784255  0.976008  0.700844  0.198261  0.012993   
2022-03-20  0.056610  0.093454  0.749417  0.463115  0.473970  0.611018   

                   6  
2022-03-14  0.538552  
2022-03-15  0.532367  
2022-03-16  0.353272  
2022-03-17  0.113220  
2022-03-18  0.453667  
2022-03-19  0.081116  
2022-03-20  0.189629

In [82]:
dframe.columns = ['C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7']
dframe

C1        C2        C3        C4        C5        C6  \
2022-03-14  0.438155  0.250915  0.541647  0.426503  0.395947  0.392830   
2022-03-15  0.332700  0.811214  0.613356  0.370942  0.010496  0.440792   
2022-03-16  0.150634  0.981007  0.822293  0.455902  0.300176  0.605559   
2022-03-17  0.358566  0.682160  0.046601  0.937919  0.743502  0.194696   
2022-03-18  0.005586  0.265114  0.881359  0.257684  0.883598  0.299040   
2022-03-19  0.475876  0.784255  0.976008  0.700844  0.198261  0.012993   
2022-03-20  0.056610  0.093454  0.749417  0.463115  0.473970  0.611018   

                  C7  
2022-03-14  0.538552  
2022-03-15  0.532367  
2022-03-16  0.353272  
2022-03-17  0.113220  
2022-03-18  0.453667  
2022-03-19  0.081116  
2022-03-20  0.189629

In [83]:
dframe.sort_values(by = 'C1') #ascending yani artan sırada sıralama yapar

C1        C2        C3        C4        C5        C6  \
2022-03-18  0.005586  0.265114  0.881359  0.257684  0.883598  0.299040   
2022-03-20  0.056610  0.093454  0.749417  0.463115  0.473970  0.611018   
2022-03-16  0.150634  0.981007  0.822293  0.455902  0.300176  0.605559   
2022-03-15  0.332700  0.811214  0.613356  0.370942  0.010496  0.440792   
2022-03-17  0.358566  0.682160  0.046601  0.937919  0.743502  0.194696   
2022-03-14  0.438155  0.250915  0.541647  0.426503  0.395947  0.392830   
2022-03-19  0.475876  0.784255  0.976008  0.700844  0.198261  0.012993   

                  C7  
2022-03-18  0.453667  
2022-03-20  0.189629  
2022-03-16  0.353272  
2022-03-15  0.532367  
2022-03-17  0.113220  
2022-03-14  0.538552  
2022-03-19  0.081116

In [84]:
dframe.sort_values(by='C1', ascending = False)

C1        C2        C3        C4        C5        C6  \
2022-03-19  0.475876  0.784255  0.976008  0.700844  0.198261  0.012993   
2022-03-14  0.438155  0.250915  0.541647  0.426503  0.395947  0.392830   
2022-03-17  0.358566  0.682160  0.046601  0.937919  0.743502  0.194696   
2022-03-15  0.332700  0.811214  0.613356  0.370942  0.010496  0.440792   
2022-03-16  0.150634  0.981007  0.822293  0.455902  0.300176  0.605559   
2022-03-20  0.056610  0.093454  0.749417  0.463115  0.473970  0.611018   
2022-03-18  0.005586  0.265114  0.881359  0.257684  0.883598  0.299040   

                  C7  
2022-03-19  0.081116  
2022-03-14  0.538552  
2022-03-17  0.113220  
2022-03-15  0.532367  
2022-03-16  0.353272  
2022-03-20  0.189629  
2022-03-18  0.453667

In [87]:
df0

ID  Name
0   1  Dogu
1   2  Bati
2   3  Ross
3   4  John

In [89]:
del df0['Name']

In [90]:
df0

ID
0   1
1   2
2   3
3   4

In [91]:
df5

a   b     c   d
row1  1   2   NaN NaN
row2  5  10  20.0 NaN

In [92]:
df5.pop('c')

row1     NaN
row2    20.0
Name: c, dtype: float64

In [101]:
col1 = np.linspace(10, 100, 30)
col2 = np.random.randint(10, 100, 30)
df10 = pd.DataFrame({'C1':col1, 'C2':col2})
df10

C1  C2
0    10.000000  22
1    13.103448  78
2    16.206897  90
3    19.310345  97
4    22.413793  58
5    25.517241  24
6    28.620690  40
7    31.724138  94
8    34.827586  57
9    37.931034  78
10   41.034483  90
11   44.137931  74
12   47.241379  71
13   50.344828  93
14   53.448276  73
15   56.551724  75
16   59.655172  39
17   62.758621  44
18   65.862069  43
19   68.965517  86
20   72.068966  99
21   75.172414  39
22   78.275862  96
23   81.379310  93
24   84.482759  24
25   87.586207  71
26   90.689655  80
27   93.793103  75
28   96.896552  33
29  100.000000  89

In [102]:
df10 = df10.drop([17, 18, 19], axis = 0)
df10

C1  C2
0    10.000000  22
1    13.103448  78
2    16.206897  90
3    19.310345  97
4    22.413793  58
5    25.517241  24
6    28.620690  40
7    31.724138  94
8    34.827586  57
9    37.931034  78
10   41.034483  90
11   44.137931  74
12   47.241379  71
13   50.344828  93
14   53.448276  73
15   56.551724  75
16   59.655172  39
20   72.068966  99
21   75.172414  39
22   78.275862  96
23   81.379310  93
24   84.482759  24
25   87.586207  71
26   90.689655  80
27   93.793103  75
28   96.896552  33
29  100.000000  89

In [103]:
df10.drop([16], axis = 0, inplace = True)
df10

C1  C2
0    10.000000  22
1    13.103448  78
2    16.206897  90
3    19.310345  97
4    22.413793  58
5    25.517241  24
6    28.620690  40
7    31.724138  94
8    34.827586  57
9    37.931034  78
10   41.034483  90
11   44.137931  74
12   47.241379  71
13   50.344828  93
14   53.448276  73
15   56.551724  75
20   72.068966  99
21   75.172414  39
22   78.275862  96
23   81.379310  93
24   84.482759  24
25   87.586207  71
26   90.689655  80
27   93.793103  75
28   96.896552  33
29  100.000000  89

In [104]:
df10.drop(df10.index[5], inplace = True)
df10

C1  C2
0    10.000000  22
1    13.103448  78
2    16.206897  90
3    19.310345  97
4    22.413793  58
6    28.620690  40
7    31.724138  94
8    34.827586  57
9    37.931034  78
10   41.034483  90
11   44.137931  74
12   47.241379  71
13   50.344828  93
14   53.448276  73
15   56.551724  75
20   72.068966  99
21   75.172414  39
22   78.275862  96
23   81.379310  93
24   84.482759  24
25   87.586207  71
26   90.689655  80
27   93.793103  75
28   96.896552  33
29  100.000000  89

In [105]:
df10 = df10.iloc[3:,]
df10

C1  C2
3    19.310345  97
4    22.413793  58
6    28.620690  40
7    31.724138  94
8    34.827586  57
9    37.931034  78
10   41.034483  90
11   44.137931  74
12   47.241379  71
13   50.344828  93
14   53.448276  73
15   56.551724  75
20   72.068966  99
21   75.172414  39
22   78.275862  96
23   81.379310  93
24   84.482759  24
25   87.586207  71
26   90.689655  80
27   93.793103  75
28   96.896552  33
29  100.000000  89

In [106]:
df10 = df10.iloc[:-4,]
df10

C1  C2
3   19.310345  97
4   22.413793  58
6   28.620690  40
7   31.724138  94
8   34.827586  57
9   37.931034  78
10  41.034483  90
11  44.137931  74
12  47.241379  71
13  50.344828  93
14  53.448276  73
15  56.551724  75
20  72.068966  99
21  75.172414  39
22  78.275862  96
23  81.379310  93
24  84.482759  24
25  87.586207  71